---

name: Build and Deploy Image

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "development"
      - "staging"
      - "main"

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      iteration_id: ${{ steps.hcp.outputs.iteration_id }}
      
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-public-vault-08c44092.b76a1ca6.z1.hashicorp.cloud:8200
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          namespace: admin
          secrets: |
            azure/creds/github-app client_id | CLIENT_ID ;
            azure/creds/github-app client_secret | CLIENT_SECRET ;
            hcp/data/packer/github-sp AZURE_SUBSCRIPTION_ID | SUBSCRIPTION_ID ;
            hcp/data/packer/github-sp TENANT_ID | TENANT_ID ;
            hcp/data/packer/github-sp HCP_CLIENT_ID | HCP_CLIENT_ID ;
            hcp/data/packer/github-sp HCP_CLIENT_SECRET | HCP_CLIENT_SECRET
            
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      # validate templates
      - name: Validate Packer Syntax
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ubuntu.pkr.hcl

      - name: Packer Init
        run: packer init .
        
      - name: Packer Build - Branches
        if: "startsWith(github.ref, 'refs/heads/')"
        run: packer build .

      - name: Packer Build - Tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: HCP_PACKER_BUILD_FINGERPRINT=$(date +'%m%d%YT%H%M%S') packer build .

      # build artifact
#      - name: Build Image
#        uses: hashicorp/packer-github-actions@master
#        with:
#          command: build
#          arguments: "-color=false -on-error=abort"
#          target: ubuntu.pkr.hcl
#        env:
#          PACKER_LOG: 1

      # additional steps to process artifacts
