---

name: Packer Build

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-public-vault-08c44092.b76a1ca6.z1.hashicorp.cloud:8200
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          namespace: admin
          secrets: |
            azure/creds/github-app client_id | CLIENT_ID ;
            azure/creds/github-app client_secret | CLIENT_SECRET ;
            hcp/data/packer/github-sp AZURE_SUBSCRIPTION_ID | SUBSCRIPTION_ID ;
            hcp/data/packer/github-sp TENANT_ID | TENANT_ID ;
            hcp/data/packer/github-sp HCP_CLIENT_ID | HCP_CLIENT_ID ;
            hcp/data/packer/github-sp HCP_CLIENT_SECRET | HCP_CLIENT_SECRET
            
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ubuntu.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ubuntu.pkr.hcl
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts
